import {
  faSpinner,
  faUtensils,
  faArrowUp,
  faChevronRight,
  faCaretDown,
  faLocationDot,
  faPhone,
  faEnvelopeOpen,
  faBars,
  faX,
  faCartPlus,
  faUserTie,
  faHeadset,
  faBurger,
  faCoffee,
  faPlay,
  faQuoteRight,
} from '@fortawesome/free-solid-svg-icons';
import {
  faFacebook,
  faFacebookF,
  faTwitter,
  faXTwitter,
  faLinkedin,
  faLinkedinIn,
  faYoutube,
} from '@fortawesome/free-brands-svg-icons';

export const solidIcons = [
  faSpinner,
  faUtensils,
  faArrowUp,
  faChevronRight,
  faCaretDown,
  faLocationDot,
  faPhone,
  faEnvelopeOpen,
  faBars,
  faX,
  faCartPlus,
  faUserTie,
  faHeadset,
  faBurger,
  faCoffee,
  faPlay,
  faQuoteRight,
];
export const brandIcons = [
  faFacebook,
  faFacebookF,
  faTwitter,
  faXTwitter,
  faLinkedin,
  faLinkedinIn,
  faYoutube,
];
